version: '2'
services:
    dataveri-app:
        image: dataveri
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dataveri-mysql:3306/dataveri?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=dataveri-elasticsearch:9300
        ports:
            - 8080:8080
    dataveri-mysql:
        extends:
            file: mysql.yml
            service: dataveri-mysql
    dataveri-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dataveri-elasticsearch
